<div class="row marketing">
<div class="col-lg-6">
    <h4>OPENY Gas Stations</h4>
    <ul>
        <li><a href="<?php echo $this->url('monitor', array('action'=>'status')); ?>" target="iframe_a">Status</a></li>
        <li><a href="<?php echo $this->url('monitor', array('action'=>'posmonitor')); ?>" target="iframe_a">Monitor OPY 1</a></li>            
    </ul>
    
        
</div>

<div class="col-lg-6">
    <h4>Authorization</h4>
    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>    
</div>

</div>
<div>
<div class="col-lg-12">
    <h4>Monitor</h4>
    <p>Please, click on disconnet when finish</p>
    <iframe src="demo_iframe.htm" name="iframe_a" style="border:5px dotted red; width:100%; height:500px"></iframe>
</div>
</div>