<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="/assets/css/status.css">
	<link rel="stylesheet" type="text/css" href="/css/iphone5.css" media="screen">
	<title>Phone Emulator</title>	
	<style>
		iframe::-webkit-scrollbar	{display: none;}
		iframe						{overflow-y:hidden;}
	</style>
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="mobile-web-app-capable" content="yes">
</head>
<body style="">
    <div id="container">
        <?php echo $this->content; ?>
    </div>
</body>
</html>