<!DOCTYPE html>
<html class="_gmaps_cdv_" style="background-color: rgba(0, 0, 0, 0);">
<head>	
	<style type="text/css">
		@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}
	</style>
    
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://192.168.0.103:35729 http://192.168.0.17:35729 http://192.168.56.1:8100 http://192.168.1.104:35729">
    
    <?php echo $this->headTitle() ?>
    <?php //echo $this->headTitle($this->translate('Log in on '). 'Orkestor')->setSeparator(' - ')->setAutoEscape(false) ?>
    <link href="/lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <script src="/lib/ionic/js/ionic.bundle.js"></script>
    <script src="/js/angular.es.js"></script>
    <script src="/js/app.js"></script>

</head>

<body ng-app="starter" class="platform-android platform-cordova platform-webview grade-a platform-android4 platform-android4_4 platform-ready _gmaps_cdv_" style="background-color: rgba(0, 0, 0, 0);">
    <ion-nav-view class="view-container _gmaps_cdv_" nav-view-transition="android" nav-view-direction="none" nav-swipe="" style="background-color: rgba(0, 0, 0, 0);">
    <ion-side-menus enable-menu-with-back-views="false" class="pane view _gmaps_cdv_" nav-view="active" style="-webkit-transform: translate3d(0%, 0px, 0px); background-color: rgba(0, 0, 0, 0);">
    <ion-side-menu-content class="menu-content pane _gmaps_cdv_ menu-animated" style="-webkit-transform: translate3d(0px, 0px, 0px); background-color: rgba(0, 0, 0, 0);">
  	<ion-nav-view class="view-container _gmaps_cdv_" nav-view-transition="android" nav-view-direction="none" nav-swipe="" style="background-color: rgba(0, 0, 0, 0);">
	<ion-view class="pane" nav-view="active" style="-webkit-transform: translate3d(0%, 0px, 0px);"> 
	<ion-nav-view class="view-container" nav-view-transition="android" nav-view-direction="forward" nav-swipe="">
	<ion-view view-title="Política de privacidad" class="pane" nav-view="active" style="-webkit-transform: translate3d(0%, 0px, 0px);"> 
	<ion-content class="padding privacy scroll-content ionic-scroll">
			<div class="scroll" style="-webkit-transform: translate3d(0px, 0px, 0px) scale(1);">
				<?php echo $this->content; ?>				
			</div>
			<div class="scroll-bar scroll-bar-v">
				<div class="scroll-bar-indicator scroll-bar-fade-out"
					style="-webkit-transform: translate3d(0px, 0px, 0px) scaleY(1); height: 246px;"></div>
			</div>
	</ion-content> 
	</ion-view>
	</ion-nav-view> 
	</ion-view>
	</ion-nav-view>
    </ion-side-menu-content>
	</ion-side-menus>
	</ion-nav-view>

</body>
</html>