<div class="row marketing">
<div class="col-lg-6">
    <h4>Import to DB Official ES Gas Stations</h4>
    <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
    <a href="<?php echo $this->url('admin', array('action'=>'importGes')); ?>">Import</a>    
</div>

<div class="col-lg-6">
    <h4>Authorization</h4>
    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
</div>
</div>