<div style="width:220px; float:left;">
    <h1>iOS Emulator</h1>
    <p>     
            <table class="striped">
    			<tbody><tr>
    				<td>Manufacturer</td>
    				<td class="data">Apple</td>
    			</tr>
    			<tr>
    				<td>Name</td>
    				<td class="data">iPhone 5</td>
    			</tr>
    			<tr>
    				<td>Css resolution</td>
    				<td class="data">320x568</td>
    			</tr>
    			<tr>
    				<td>Pixel resolution</td>
    				<td class="data">640x1136</td>
    			</tr>
    			<tr>
    				<td>Operating system</td>
    				<td class="data">iOS 6.0</td>
    			</tr>
    			<tr>
    				<td>Year released</td>
    				<td class="data">2012</td>
    			</tr>
    			<tr>
    				<td>Device type</td>
    				<td class="data">Phone</td>
    			</tr>
    			<tr>
    				<td>URL Ref</td>
    				<td class="data">http://mobiletest.me/</td>
    			</tr>    			
    		</tbody></table>
    </p>            
</div>

<div style="float:right">        		
    <div id="iphone_5_emulator" style="transform: scale(1); transform-origin: 0px 0px 0px;">												
        <div id="frame_iphone_5_emulator" class="frame_scroller">													
        <iframe src="<?php echo $this->urlframe;?>" frameborder="0" style="background-color: #fff;"></iframe>												
        </div>											
    </div>
</div>