<h1><strong>Indice</strong></h1>
<ol>
	<li>
		<a href="<?php echo $this->url('appframe', array('action'=>'faq')); ?>">FAQ</a>
	</li>
	<li>
		<a href="<?php echo $this->url('appframe', array('action'=>'privacy')); ?>">Política de privacidad</a>
	</li>
	<li>
		<a href="<?php echo $this->url('appframe', array('action'=>'terms')); ?>">Términos de uso</a>
	</li>
	<li>
		<a href="<?php echo $this->url('appframe', array('action'=>'refuel')); ?>">Refuel</a>
	</li>
	<li>
		<a href="<?php echo $this->url('appframe', array('action'=>'tren')); ?>">Autolavado</a>
	</li>
	<li>
		<a href="<?php echo $this->url('appframe', array('action'=>'tren2')); ?>">Autolavado 2</a>
	</li>
</ol>
