<?php
$title = 'Política de privacidad';
$this->headTitle($title);
?>
<h1><strong>Política de privacidad</strong></h1>
<ol>
	<li>
		<h4>Incorporación de datos personales a los ficheros de Openy</h4>
		<p>De conformidad con lo establecido en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal (en
			adelante, “LOPD”), se informa que todos los datos personales que el Usuario facilite a través de este Sitio Web, incluyendo su
			dirección IP, serán incorporados y tratados en los ficheros titularidad de Openy para posibilitar la prestación de los
			servicios solicitados por el Usuario y mantenerle comercialmente informado, incluso por medios electrónicos, sobre las novedades,
			productos y servicios de Openy y las sociedades de su grupo empresarial dedicadas a su mismo sector de actividad. Si el Usuario
			no desea recibir este tipo de comunicaciones, puede indicarlo en cualquier momento mediante correo electrónico dirigido a
			info@openy.es.</p>
	</li>
	<li>
		<h4>Ejercicio de derechos</h4>
		<p>El Usuario puede ejercer sus derechos de acceso, rectificación, cancelación y oposición previstos en la LOPD,
			mediante una comunicación escrita dirigida a Openy, c C/ Po Mestre nº 10 2ª-1ª, Moja-Olèrdola , 08734; o bien mediante correo
			electrónico dirigido a info@openy.es. En ambos casos el Usuario interesado deberá acompañar una copia de su documento nacional de
			identidad, pasaporte u otro documento válido que le identifique.</p>
	</li>
	<li>
		<h4>Medidas de seguridad</h4>
		<p>Los datos personales del Usuario serán tratados por Openy bajo la más estricta confidencialidad, aplicando las medidas de
			seguridad técnicas y organizativas que correspondan conforme a la legislación aplicable.</p>
	</li>
	<li>
		<h4>Prohibición para menores</h4>
		<p>Los menores de 14 años no deben facilitar sus datos personales a Openy sin el previo consentimiento de sus padres o
			tutores. Por favor, si eres menor pide antes a tus padres o tutores que se pongan en contacto con nosotros.</p>
	</li>
	<li>
		<h4>Datos de terceros</h4>
		<p>El Usuario tiene terminantemente prohibido facilitar en el Sitio Web datos personales, incluyendo la imagen, de terceras
			personas. El Usuario se obliga a mantener indemne a Openy ante cualquier posible reclamación, pena, multa o sanción que pueda
			venir obligada a soportar como consecuencia del incumplimiento por parte del Usuario del deber descrito en este párrafo.</p>
	</li>
</ol>
