<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    
    <?php echo $this->headTitle() ?>
    
    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="data:text/css;charset=utf-8," data-href="/vendor/bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet" id="bs-theme-stylesheet">
    <!-- Documentation extras -->
    <link href="/assets/css/docs.min.css" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="/assets/css/style.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/assets/js/ie-emulation-modes-warning.js"></script>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- Favicons -->
    <link rel="icon" href="/assets/ico/favicon.png">
    <link rel="apple-touch-icon" href="/assets/ico/apple-touch-icon.png">
    
    <!-- Analytics -->
    <script>
      
    </script>
    
  </head>
  <body>
    <a id="skippy" class="sr-only sr-only-focusable" href="#content"><div class="container"><span class="skiplink-text">Skip to main content</span></div></a>

    <!-- Header Nav
    ================================================== -->
    <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="../" class="navbar-brand openy-orange">Openy</a>
        </div>
        
        <nav id="bs-navbar" class="collapse navbar-collapse">
                    <?php if ($this->layout()->loginbtn):?>
                        <?php 
						echo "<ul class=\"nav navbar-nav\">";
						$navHelper = $this->navigation('userauth');
						$containers = $navHelper->getContainer();
						
						
						foreach($containers->getPages() as $page) 
						{
						 
							$class = "";
							if ($page->isActive()) {
								$class = "active";
							}
							if(count($page)) 
							{
								// if there are subpages we render the menu a bit different
								$label = $page->getLabel();
								$label = $this->translate($label); // translated label
								$label = $this->escapehtml($label); // sanitized label
								printf('<li class="dropdown%s">'."\n",
										($class?' '.$class:'')
								);
								printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b
											class="caret"></b></a>'."\n",
											$page->getHref(),
											$label
								);
								echo '<ul class="dropdown-menu">'."\n";
								foreach($page as $subPage) 
								{
									if(!$navHelper->accept($subPage)) 
									{
										continue;
									}
									printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
								}
								echo "</ul></li>\n";
							}
							else 
							{
								printf("<li class=\"%s\">%s</li>\n",
								$class,$navHelper->htmlify($page));
							}
						}
						echo "</ul>";						
					   ?>
					<?php endif;?>
					<?php 
						echo "<ul class=\"nav navbar-nav\">";
						$navHelper = $this->navigation('default');
						$containers = $navHelper->getContainer();
						
						
						foreach($containers->getPages() as $page) 
						{
						 
							$class = "";
							if ($page->isActive()) {
								$class = "active";
							}
							if(count($page)) 
							{
								// if there are subpages we render the menu a bit different
								$label = $page->getLabel();
								$label = $this->translate($label); // translated label
								$label = $this->escapehtml($label); // sanitized label
								printf('<li class="dropdown%s">'."\n",
										($class?' '.$class:'')
								);
								printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b
											class="caret"></b></a>'."\n",
											$page->getHref(),
											$label
								);
								echo '<ul class="dropdown-menu">'."\n";
								foreach($page as $subPage) 
								{
									if(!$navHelper->accept($subPage)) 
									{
										continue;
									}
									printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
								}
								echo "</ul></li>\n";
							}
							else 
							{
								printf("<li class=\"%s\">%s</li>\n",
								$class,$navHelper->htmlify($page));
							}
						}
						echo "</ul>";						
					?>
          
          <ul class="nav navbar-nav navbar-right">
            <?php if ($this->layout()->loginbtn):?><li><a href="/auth/logout" >Logout</a></li><?php endif;?>
            <li><a href="http://openy.es" >Website</a></li>
          </ul>
        </nav>
      </div>
    </header> <!-- /Header Nav -->
    

    <!-- Page Header -->
    <?php /*?>
    <h3 class="text-muted orkestor"><a href="/" style="text-decoration:none"><?php echo $this->sitevars('name');?></a></h3>
    <div class="bs-docs-header" id="content" tabindex="-1">
      <div class="container">
        <h1>CSS</h1>
        <p>Global CSS settings, fundamental HTML elements styled and enhanced with extensible classes, and an advanced grid system.</p>
        <div id="carbonads-container"><div class="carbonad"><div id="azcarbon"></div><script>var z = document.createElement("script"); z.async = true; z.src = "http://engine.carbonads.com/z/32341/azcarbon_2_1_0_HORIZ"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(z, s);</script></div></div>

      </div>
    </div> <!-- /Page Header -->
    <?php */?>

    
    		     
    <div class="container bs-docs-container">
            <br/><br/>
            <!-- Breadcrumb
            ================================================== -->
            <?php
                if($this->navigation('navigation')!=='')
                    echo $this->navigation('navigation') // <-- Update this!!
		                      ->breadcrumbs()
		                      ->setMinDepth(0)
		                      ->setPartial(array('partial/breadcrumb.phtml', 'Album'));
		     ?>
		     <br/>
    
    <!-- Row
    ================================================== -->		     
    <div class="row"> 
      
        <!-- Content
        ================================================== -->
        <?php echo $this->content; ?>
       
        
    </div> <!-- /Row -->
</div> <!-- /Container -->

<!-- Footer
================================================== -->
<?php echo $this->partial('partial/adminfooter.phtml'); ?> 








    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/assets/js/ie10-viewport-bug-workaround.js"></script>
    
    <!-- Twitter
    ================================================== -->
    <script>
      
    </script>
    
    <!-- Analytics
    ================================================== -->
    <script>
      
    </script>

  </body>
</html>