<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/assets/ico/favicon.png">

    
    <?php echo $this->headTitle() ?>
    

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/css/docs.min.css" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="/assets/css/jumbotron-narrow.css" rel="stylesheet">
    <link href="/assets/css/style.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/assets/js/ie-emulation-modes-warning.js"></script>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>



    <div class="container">
      <div class="header">
        <nav>
        
                    <ul class="nav navbar-nav">
	                    <?php 
// 						 $this->navigation('navigation')
// 						           ->menu()
// 						           ->setMinDepth(0)
// 						           ->setMaxDepth(0)
// 						           ->setUlClass('nav navbar-nav');
						 ?>						                    
                    </ul>
                    
                    <?php if ($this->layout()->loginbtn):?>
                        <?php 
						echo "<ul class=\"nav nav-pills pull-right\">";
						$navHelper = $this->navigation('userauth');
						$containers = $navHelper->getContainer();
						
						
						foreach($containers->getPages() as $page) 
						{
						 
							$class = "";
							if ($page->isActive()) {
								$class = "active";
							}
							if(count($page)) 
							{
								// if there are subpages we render the menu a bit different
								$label = $page->getLabel();
								$label = $this->translate($label); // translated label
								$label = $this->escapehtml($label); // sanitized label
								printf('<li class="dropdown%s">'."\n",
										($class?' '.$class:'')
								);
								printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b
											class="caret"></b></a>'."\n",
											$page->getHref(),
											$label
								);
								echo '<ul class="dropdown-menu">'."\n";
								foreach($page as $subPage) 
								{
									if(!$navHelper->accept($subPage)) 
									{
										continue;
									}
									printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
								}
								echo "</ul></li>\n";
							}
							else 
							{
								printf("<li class=\"%s\">%s</li>\n",
								$class,$navHelper->htmlify($page));
							}
						}
						echo "</ul>";						
					   ?>
					<?php endif;?>
					
					
					
					
                 <?php 
						echo "<ul class=\"nav nav-pills pull-right\">";
						$navHelper = $this->navigation('default');
						$containers = $navHelper->getContainer();
						
						
						foreach($containers->getPages() as $page) 
						{
						 
							$class = "";
							if ($page->isActive()) {
								$class = "active";
							}
							if(count($page)) 
							{
								// if there are subpages we render the menu a bit different
								$label = $page->getLabel();
								$label = $this->translate($label); // translated label
								$label = $this->escapehtml($label); // sanitized label
								printf('<li class="dropdown%s">'."\n",
										($class?' '.$class:'')
								);
								printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b
											class="caret"></b></a>'."\n",
											$page->getHref(),
											$label
								);
								echo '<ul class="dropdown-menu">'."\n";
								foreach($page as $subPage) 
								{
									if(!$navHelper->accept($subPage)) 
									{
										continue;
									}
									printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
								}
								echo "</ul></li>\n";
							}
							else 
							{
								printf("<li class=\"%s\">%s</li>\n",
								$class,$navHelper->htmlify($page));
							}
						}
						echo "</ul>";						
					?>
					
        </nav>
        <h3 class="text-muted orkestor"><a href="/" style="text-decoration:none"><?php echo $this->sitevars('name');?></a></h3>
        
      </div>
        
      
      
      <div class="container">
            <?php
            if($this->navigation('navigation')!=='')
    		     echo $this->navigation('navigation') // <-- Update this!!
    		               ->breadcrumbs()
    		               ->setMinDepth(0)
    		               ->setPartial(array('partial/breadcrumb.phtml', 'Album'));
    		     ?>
            <?php echo $this->content; ?>
        
        </div> <!-- /container -->
        
        
        <br/><br/><br/>
        <?php echo $this->partial('partial/footer.phtml'); ?> 
      

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
