<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/assets/ico/favicon.png">

    
    <?php echo $this->headTitle() ?>
    

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/css/docs.min.css" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="/assets/css/jumbotron.css" rel="stylesheet">
    <link href="/assets/css/style.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/assets/js/ie-emulation-modes-warning.js"></script>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
<header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="../" class="navbar-brand">Bootstrap</a>
    </div>
    <nav id="bs-navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="../getting-started/">Getting started</a>
        </li>
        <li class="active">
          <a href="../css/">CSS</a>
        </li>
        <li>
          <a href="../components/">Components</a>
        </li>
        <li>
          <a href="../javascript/">JavaScript</a>
        </li>
        <li>
          <a href="../customize/">Customize</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://expo.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Expo</a></li>
        <li><a href="http://blog.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Blog');">Blog</a></li>
      </ul>
    </nav>
  </div>
</header>
    <nav class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="header">
        <nav>
        
          <ul class="nav navbar-nav">
	                    <?php 
// 						 $this->navigation('navigation')
// 						           ->menu()
// 						           ->setMinDepth(0)
// 						           ->setMaxDepth(0)
// 						           ->setUlClass('nav navbar-nav');
						 ?>						                    
                    </ul>
                    
                    <?php if ($this->layout()->loginbtn):?>
                        <?php 
						echo "<ul class=\"nav nav-pills pull-right\">";
						$navHelper = $this->navigation('userauth');
						$containers = $navHelper->getContainer();
						
						
						foreach($containers->getPages() as $page) 
						{
						 
							$class = "";
							if ($page->isActive()) {
								$class = "active";
							}
							if(count($page)) 
							{
								// if there are subpages we render the menu a bit different
								$label = $page->getLabel();
								$label = $this->translate($label); // translated label
								$label = $this->escapehtml($label); // sanitized label
								printf('<li class="dropdown%s">'."\n",
										($class?' '.$class:'')
								);
								printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b
											class="caret"></b></a>'."\n",
											$page->getHref(),
											$label
								);
								echo '<ul class="dropdown-menu">'."\n";
								foreach($page as $subPage) 
								{
									if(!$navHelper->accept($subPage)) 
									{
										continue;
									}
									printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
								}
								echo "</ul></li>\n";
							}
							else 
							{
								printf("<li class=\"%s\">%s</li>\n",
								$class,$navHelper->htmlify($page));
							}
						}
						echo "</ul>";						
					   ?>
					<?php endif;?>
					
					
					
					
                 <?php 
						echo "<ul class=\"nav nav-pills pull-right\">";
						$navHelper = $this->navigation('default');
						$containers = $navHelper->getContainer();
						
						
						foreach($containers->getPages() as $page) 
						{
						 
							$class = "";
							if ($page->isActive()) {
								$class = "active";
							}
							if(count($page)) 
							{
								// if there are subpages we render the menu a bit different
								$label = $page->getLabel();
								$label = $this->translate($label); // translated label
								$label = $this->escapehtml($label); // sanitized label
								printf('<li class="dropdown%s">'."\n",
										($class?' '.$class:'')
								);
								printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b
											class="caret"></b></a>'."\n",
											$page->getHref(),
											$label
								);
								echo '<ul class="dropdown-menu">'."\n";
								foreach($page as $subPage) 
								{
									if(!$navHelper->accept($subPage)) 
									{
										continue;
									}
									printf("<li>%s</li>\n",$navHelper->htmlify($subPage));
								}
								echo "</ul></li>\n";
							}
							else 
							{
								printf("<li class=\"%s\">%s</li>\n",
								$class,$navHelper->htmlify($page));
							}
						}
						echo "</ul>";						
					?>
					
        </nav>
        <h3 class="text-muted orkestor"><a href="/" style="text-decoration:none"><?php echo $this->sitevars('name');?></a></h3>
        
      </div>
        
      
      
      <div class="container">
            <?php
            if($this->navigation('navigation')!=='')
    		     echo $this->navigation('navigation') // <-- Update this!!
    		               ->breadcrumbs()
    		               ->setMinDepth(0)
    		               ->setPartial(array('partial/breadcrumb.phtml', 'Album'));
    		     ?>
            <?php echo $this->content; ?>
        
        </div> <!-- /container -->
        
        
        <br/><br/><br/>
        <?php echo $this->partial('partial/footer.phtml'); ?> 
      

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
