<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Documentation')); ?></h1><br/>
    <p><?php echo sprintf($this->translate('Openy documetation'));?></p>
    <p><?php echo sprintf($this->translate('Visit %sOpeny website%s or %sGas stations website%s.'), 
                                            '<a href="http://openy.es" target="_blank">', '</a>', 
                                            '<a href="http://tugasolinera.openy.es" target="_blank">', '</a>') 
        ?>
    </p>    
</div>

<div class="row">


  
</div>
