<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.png">

    <title>Sticky Footer Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="sticky-footer.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>Openy recover password</h1>
      </div>
      <p class="lead">
            <p>Hola <?php echo $this->name; ?>,</p>
            Has solicitado recordar tu contraseña de <strong>Openy</strong>.
        </p><p>
            
            Ahora necesitas <a href="<?php echo $this->activationURL.$this->link; ?>" target="_blank">establer la nueva contraseña</a>.
            Ten presente que el link será válido una sola vez y por 24 horas.
            </p>
            
            <p>
            Si recibiste este email por error, o si no has perdido tu password, no necesitas hacer nada. Solo haz caso omiso de este mensaje.
            Pero si crees que <strong>es muy extraño</strong>, puedes <a href="http://www.openy.com/contact" target="_blank">informarnos</a>, que con gusto te ayudaremos.
            </p>            
      </p>
      <p>
            <p>
            Si las URL de este mensaje no funcionan al hacer clic en ellas,
            pégalas en la barra de direcciones del navegador.
            </p>
            <p>
            URL para establecer nueva contraseña: <?php echo $this->activationURL.$this->link; ?>
            </p>
      </p>      
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">
            <p>
                <strong>Gracias por tu atención,</strong>
            </p>
            El equipo de <a href="http://www.openy.com" target="_blank">openy</a>.
        </p>
      </div>
    </footer>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
