<div class="jumbotron">
        <h1><?php echo $this->sitevars('name');?></h1>
        <p class="lead">The Api Documentation site for our software. <br/>You gonna need a key!</p>
        <p>
        <a class="btn btn-lg btn-success" href="<?php echo $this->url('login/process'); ?>" role="button">Log in</a>
        

        </p>
      </div>
    
    
      <div class="row marketing">
        <div class="col-lg-6">
          <h4>RESTful</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Json+HAL</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>API Problem</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Versioning</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Validation</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Authorization</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>