<footer class="bs-docs-footer" role="contentinfo">
  <div class="container">
    <p>&copy; <?php echo $this->sitevars('name');?> 2013 - <?php echo date('Y') ?>. <?php echo $this->translate('All rights reserved.') ?></p>
    <div class="bs-docs-social">
      <ul class="bs-docs-social-buttons">
        
        <li class="follow-btn">
          <a href="https://tugasolinera.openy.es"  data-link-color="#0069D6" data-show-count="true">TuGasolinera</a>
        </li>
        <li class="tweet-btn">
          <a href="https://openy.es"  >Openy.es</a>
        </li>
      </ul>
    </div>


    <ul class="bs-docs-footer-links text-muted">
      <li>Currently v0.0.1</li>
      <li>&middot;</li>
      <li><?php echo date('Y m') ?></li>
      
    </ul>
  </div>
</footer>